Start fixing master handling on Debian in webrick mode (#7).
The way I understand
https://docs.puppetlabs.com/puppet/latest/reference/lang_relationships.html,
"subscribe" is a superset of "require", so we can drop "require" here.

This fixes:

  Error: Could not retrieve catalog from remote server:
  Error 400 on SERVER: Parameter 'require' is already set on Service[puppetmaster]
  by #<Puppet::Resource::Type:0x007f922e008a08> at /etc/puppet/modules/puppet/manifests/master/package/base.pp:9;
  cannot redefine at 24:/etc/puppet/modules/puppet/manifests/master/debian.pp
  on node host.domain